os: Visual Studio 2015

version: "{build}"
clone_folder: C:\projects\xcbuild

platform:
  - Win32
  - x64

configuration:
 - Debug

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: cd C:\projects
  - cmd: md zlib
  - cmd: cd zlib
  - cmd: appveyor DownloadFile http://zlib.net/zlib128-dll.zip
  - cmd: 7z x zlib128-dll.zip

before_build:
  - cmd: cd C:\projects\xcbuild
  - cmd: git submodule update --init
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -Bbuild -H. -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DZLIB_ROOT=C:\projects\zlib
  - cmd: cp C:\projects\zlib\zlib1.dll build

build:
  project: build\xcbuild.sln

test_script:
  - cmd: cd build
  - cmd: ctest -C %configuration% --verbose .

artifacts:
  - path: build
